# Generated by Django 4.0.5 on 2022-06-21 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=50)),
                ('datetime_created', models.DateTimeField()),
                ('calculator_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.calculatormemory')),
            ],
        ),
    ]
