# Generated by Django 4.0.5 on 2022-06-21 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatormemory',
            name='session_name',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='calculatormemory',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
